name: CI
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 26
          - 24
          - 22
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - if: ${{ matrix.node-version == 26 }}
        name: Check formatting
        run: npm run lint
      - if: ${{ matrix.node-version == 26 }}
        name: Check types
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - if: ${{ matrix.node-version == 26 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@576d21be71a620e769dc88478d7f184d5f938f0b # v2.1.2
      - if: ${{ matrix.node-version == 26 }}
        name: Check dependency owners
        uses: dependency-owners/check@a7663cf1fc4d61e717c846810c1cf7919194ada9 # v2.1.1
        with:
          dependency-file: 'package.json'
          loader: '@dependency-owners/package-json-loader'
      - if: ${{ matrix.node-version == 26 }}
        name: Assign reviewers to dependency changes
        uses: dependency-owners/assign@8480813cc5f2ba0ad8953961a9be0c08f776fd80 # v2.1.1
        with:
          dependency-file: 'package.json'
          loader: '@dependency-owners/package-json-loader'
