name: CI
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 26
          - 24
          - 22
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - if: ${{ matrix.node-version == 26 }}
        name: Check formatting
        run: npm run lint
      - if: ${{ matrix.node-version == 26 }}
        name: Check types
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - if: ${{ matrix.node-version == 26 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@7d016f859ab1635756d4f4e2e653cf9a72af4a6f # v2.0.20
      - if: ${{ matrix.node-version == 26 }}
        name: Check dependency owners
        uses: dependency-owners/check@873d9df42ed1eaa620e6def42d0756cc3008540c # v2.0.17
        with:
          dependency-file: 'package.json'
          loader: '@dependency-owners/package-json-loader'
      - if: ${{ matrix.node-version == 26 }}
        name: Assign reviewers to dependency changes
        uses: dependency-owners/assign@ac1fd950a2356ec64fe9dc92f21cd51f05aba420 # v2.0.24
        with:
          dependency-file: 'package.json'
          loader: '@dependency-owners/package-json-loader'
