name: CI
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24
          - 22
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - if: ${{ matrix.node-version == 24 }}
        name: Check formatting
        run: npm run lint
      - if: ${{ matrix.node-version == 24 }}
        name: Check types
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - if: ${{ matrix.node-version == 24 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@c3602a71c61778a0f25856f45997d334bfa05417 # v2.0.12
      - if: ${{ matrix.node-version == 24 }}
        name: Check dependency owners
        uses: dependency-owners/check@ef05177df0a5fd17be5d2b75ada149a5dc015c83 # v2.0.11
        with:
          dependency-file: 'package.json'
          loader: '@dependency-owners/package-json-loader'
      - if: ${{ matrix.node-version == 24 }}
        name: Assign reviewers to dependency changes
        uses: dependency-owners/assign@3fe3500ed1c119b1a42206db485bd95f973d4c8c # v2.0.17
        with:
          dependency-file: 'package.json'
          loader: '@dependency-owners/package-json-loader'
